name: Stage Package on npmjs

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for OIDC
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      # Ensure npm 11.15.0 or later is installed for staged publishing.
      - name: Update npm
        run: npm install -g npm@latest
      - name: Install dependencies
        run: yarn install --immutable
      - name: Stage @shortcut/client
        run: npm stage publish --access public
      - name: Rename package to @useshortcut/client
        run: npm pkg set name=@useshortcut/client
      - name: Stage @useshortcut/client
        run: npm stage publish --access public
        env:
          NPM_CONFIG_IGNORE_SCRIPTS: 'true'
